
title: RK Groups
baseurl: ""
url: "https://rk-groups.github.io"
theme: null

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO Configuration
description: "Multi-company static site for RK Groups with business tools, calculators, and company information."
author: "RK Groups"
keywords: "RK Groups, business tools, calculators, GST calculator, liquidity calculator, oxygen company, Gorakhpur"
lang: en_US
locale: en_US

# Social Media Links
social:
  name: RK Groups
  links:
    - https://github.com/rk-Groups

# Business Information
business:
  name: "RK Groups"
  type: "Organization"
  location: "Gorakhpur, Uttar Pradesh, India"

# Jekyll SEO Tag Settings
twitter:
  username: rk_groups
  card: summary_large_image

facebook:
  app_id:
  publisher:
  admins:

# Sitemap Configuration
sitemap:
  exclude:
    - /dev/
    - /README.md
    - /.git/
    - /node_modules/
