
title: RK Groups
baseurl: ""
url: "https://rk-groups.github.io"
theme: null

# Plugins
plugins:
  - jekyll-seo-tag
  # - jekyll-sitemap  # Temporarily disabled - causing build errors
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

# SEO Configuration
description: "Multi-company static site for RK Groups with business tools, calculators, and company information."
author: "RK Groups"
keywords: "RK Groups, business tools, calculators, GST calculator, liquidity calculator, oxygen company, Gorakhpur"
lang: en_US
locale: en_US

# Social Media Links
social:
  name: RK Groups
  links:
    - https://github.com/rk-Groups

# Business Information
business:
  name: "RK Groups"
  type: "Organization"
  location: "Gorakhpur, Uttar Pradesh, India"

# Jekyll SEO Tag Settings
twitter:
  username: rk_groups
  card: summary_large_image

facebook:
  app_id:
  publisher:
  admins:

# Sitemap Configuration
sitemap:
  exclude:
    - /dev/
    - /README.md
    - /.git/
    - /node_modules/

# Exclude files from processing
exclude:
  - vendor/
  - .git/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - README.md
  - sitemap.xml  # Exclude any sitemap.xml from processing

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Include/Exclude
include:
  - _pages
exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.gemspec"
  - node_modules/
  - scripts/
  - dev/
  - test-and-push.ps1
  - LOCAL_TESTING_SETUP.md

# Development settings
host: 127.0.0.1
port: 4000
livereload: true

# Compression
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  startings: [html, head, body]
  blanklines: false

# Asset optimization
sass:
  style: compressed
  sourcemap: never

# Build optimization
incremental: true
profile: false
strict_front_matter: true

# Liquid optimization
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: true
