services:
  jekyll:
    image: jekyll/jekyll:4
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --host 0.0.0.0 --livereload --drafts --incremental

volumes:
  bundle_cache: