name: 🐛 Bug Report
description: Report a bug or issue with the website
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us resolve it quickly.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the website is affected?
      options:
        - Homepage
        - Companies
        - Calculators
        - Visualizations
        - Navigation
        - Mobile/Responsive
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this issue?
      options:
        - Critical (Site broken, security issue)
        - High (Important functionality broken)
        - Medium (Feature not working as expected)
        - Low (Minor issue, cosmetic)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: "Describe the issue..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, device, and other relevant information
      placeholder: |
        - Browser: [e.g. Chrome 118, Safari 17]
        - Device: [e.g. iPhone 13, Desktop]
        - OS: [e.g. Windows 11, macOS 14]
        - Screen Size: [e.g. 1920x1080, Mobile]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information, screenshots, or logs