name: Markdown Link Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run weekly on Sundays at 12:00 UTC
    - cron: '0 12 * * 0'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for markdown files
        id: check_files
        run: |
          find . -name "*.md" -type f -not -path "./_site/*" -not -path "./node_modules/*" > markdown_files.txt
          if [ -s markdown_files.txt ]; then
            echo "markdown_files_exist=true" >> $GITHUB_OUTPUT
          else
            echo "markdown_files_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Run markdown-link-check
        if: steps.check_files.outputs.markdown_files_exist == 'true'
        run: |
          while IFS= read -r file; do
            echo "Checking $file"
            npx --yes markdown-link-check "$file" --config .github/linkcheck.config.json --quiet
          done < markdown_files.txt

      - name: Report if no markdown files found
        if: steps.check_files.outputs.markdown_files_exist == 'false'
        run: echo "No markdown files found to check."
